// <auto-generated />
using BeastMaster.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeastMaster.Migrations
{
    [DbContext(typeof(BeastMasterContext))]
    [Migration("20200818172850_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BeastMaster.Models.Creature", b =>
                {
                    b.Property<int>("CreatureId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatureAbility");

                    b.Property<string>("CreatureDescription");

                    b.Property<string>("CreatureHabitat");

                    b.Property<string>("CreatureImage");

                    b.Property<string>("CreatureLifespan");

                    b.Property<string>("CreatureMorality");

                    b.Property<string>("CreatureName");

                    b.Property<string>("CreatureNemesis");

                    b.Property<string>("CreatureOriginCulture");

                    b.Property<string>("CreatureOriginDate");

                    b.Property<string>("CreatureRelatedCreature");

                    b.Property<string>("CreatureTaxonomy");

                    b.Property<string>("CreatureType");

                    b.Property<string>("CreatureWeakness");

                    b.Property<string>("Gender");

                    b.HasKey("CreatureId");

                    b.ToTable("Creatures");
                });
#pragma warning restore 612, 618
        }
    }
}
