// <auto-generated />
using BeastMaster.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeastMaster.Migrations
{
    [DbContext(typeof(BeastMasterContext))]
    [Migration("20200818174842_Secondary")]
    partial class Secondary
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BeastMaster.Models.Creature", b =>
                {
                    b.Property<int>("CreatureId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatureAbility");

                    b.Property<string>("CreatureDescription");

                    b.Property<string>("CreatureHabitat");

                    b.Property<string>("CreatureImage");

                    b.Property<string>("CreatureLifespan");

                    b.Property<string>("CreatureMorality");

                    b.Property<string>("CreatureName");

                    b.Property<string>("CreatureNemesis");

                    b.Property<string>("CreatureOriginCulture");

                    b.Property<string>("CreatureOriginDate");

                    b.Property<string>("CreatureRelatedCreature");

                    b.Property<string>("CreatureTaxonomy");

                    b.Property<string>("CreatureType");

                    b.Property<string>("CreatureWeakness");

                    b.HasKey("CreatureId");

                    b.ToTable("Creatures");

                    b.HasData(
                        new
                        {
                            CreatureId = 1,
                            CreatureAbility = "Fire-Breathing",
                            CreatureDescription = "this is my description of Matilda the fire-breathing kid",
                            CreatureHabitat = "Chokey",
                            CreatureImage = "http://wwww.dummyurl.com",
                            CreatureLifespan = "86",
                            CreatureMorality = "good",
                            CreatureName = "Matilda",
                            CreatureNemesis = "mom and dad",
                            CreatureOriginDate = "1996",
                            CreatureRelatedCreature = "None",
                            CreatureTaxonomy = "Human",
                            CreatureType = "Little girl",
                            CreatureWeakness = "water"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
